// this is the client stub generated by bus compiler

class Number {
  public Number(double r, double c) {
    // talk to daemon
    throw new UnsupportedOperationException();
  }

  public void increment() {
    throw new UnsupportedOperationException();
  }

  public double getLength() {
    throw new UnsupportedOperationException();
  }

  public static Number add(Number a, Number b) {
    throw new UnsupportedOperationException();
  }

  @Override
  public String toString() {
    throw new UnsupportedOperationException();
  }
}
